# Generated by Django 5.2.16 on 2026-08-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(blank=True, default='', help_text='e.g. Engineering, Design, Marketing', max_length=100),
        ),
    ]
