# Generated by Django 5.2.16 on 2026-08-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='auto_reject_score',
            field=models.PositiveIntegerField(blank=True, help_text='If set, candidates scoring below this are auto-rejected on upload/import.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, help_text='Comma-separated required skills for auto-scoring (e.g. Python, Docker, SQL).'),
        ),
    ]
