# Generated by Django 5.2.16 on 2026-08-03 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_auto_reject_score_job_requirements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interviewround',
            index=models.Index(fields=['job', 'order'], name='ix_round_job_order'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', '-created_at'], name='ix_job_active_created'),
        ),
    ]
