# Generated by Django 5.2.16 on 2026-09-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_auto_reject_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='auto_reject_score',
            field=models.PositiveIntegerField(blank=True, help_text='Baseline minimum score (0-100). Candidates scoring below this are automatically rejected on upload/import. Leave empty to disable.', null=True),
        ),
    ]
