# Generated by Django 5.2.16 on 2026-09-05 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_auto_reject_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='auto_reject_score',
            field=models.PositiveIntegerField(blank=True, help_text='Baseline minimum score (0-100). Candidates scoring below this are automatically rejected on upload/import. Leave empty to disable.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
