# Generated by Django 5.2.16 on 2026-09-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_auto_reject_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='num_openings',
            field=models.PositiveIntegerField(default=1, help_text='Number of positions to fill for this job posting.'),
        ),
    ]
