# Generated by Django 5.2.16 on 2026-09-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_num_openings'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='domain',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('infrastructure', 'Infrastructure'), ('quality_assurance', 'Quality Assurance'), ('design', 'Design'), ('product', 'Product'), ('data', 'Data'), ('other', 'Other')], default='other', help_text='Structured functional domain, used for interviewer matching and talent-pool search.', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='seniority',
            field=models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('lead', 'Lead')], default='mid', help_text='Required seniority level. Only interviewers at or above this level can be assigned.', max_length=10),
        ),
    ]
