# Generated by Django 5.2.16 on 2026-09-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_backfill_domain_seniority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('product', 'Product'), ('design', 'Design'), ('data', 'Data'), ('infrastructure', 'Infrastructure'), ('quality_assurance', 'Quality Assurance'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('people', 'People & HR'), ('finance', 'Finance'), ('operations', 'Operations'), ('other', 'Other')], default='other', help_text='Organizational department, used for org-level reporting.', max_length=20),
        ),
    ]
