# Generated by Django 5.2.16 on 2026-09-16 15:48
#
# Depends on 0011_backfill_department_choices to run FIRST: every existing
# department value must already be normalized to one of the choice keys
# below (all <=20 chars) before this AlterField narrows the column,
# otherwise Postgres raises "value too long for type character
# varying(20)" for any pre-existing free-text value longer than 20 chars
# (e.g. "Software Engineering Department") -- reproduced live against a
# real Postgres 16 instance with the migrations in the opposite order.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_backfill_department_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('product', 'Product'), ('design', 'Design'), ('data', 'Data'), ('infrastructure', 'Infrastructure'), ('quality_assurance', 'Quality Assurance'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('people', 'People & HR'), ('finance', 'Finance'), ('operations', 'Operations'), ('other', 'Other')], default='other', help_text='Organizational department, used for org-level reporting.', max_length=20),
        ),
    ]
