# Generated by Django 5.2.16 on 2026-09-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_job_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='closure_reason',
            field=models.CharField(blank=True, choices=[('hired', 'Position filled'), ('cancelled', 'Cancelled'), ('on_hold', 'On hold'), ('other', 'Other')], help_text='Why the job was closed. Chosen at closure time; cleared on reopen.', max_length=20, null=True),
        ),
    ]
