# Generated by Django 5.2.16 on 2026-09-14 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_phase1_schema'),
        ('jobs', '0008_job_num_openings'),
        ('pipeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinemove',
            name='from_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pipelinemove',
            name='to_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pipelinemove',
            index=models.Index(fields=['to_status'], name='ix_move_to_status'),
        ),
        migrations.AddIndex(
            model_name='pipelinemove',
            index=models.Index(fields=['-moved_at'], name='ix_move_moved_at'),
        ),
    ]
