services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=True
      - DATABASE_URL=postgres://altrium:altrium_pass@db:5432/altrium_db
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: altrium_db
    environment:
      - POSTGRES_USER=altrium
      - POSTGRES_PASSWORD=altrium_pass
      - POSTGRES_DB=altrium_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
