"""
Django settings for altrium_tracker project.

Generated by 'django-admin startproject' using Django 5.2.16.
"""

from pathlib import Path

import dj_database_url
from decouple import AutoConfig

# AutoConfig searches from this file's directory upward for a local .env and
# falls back to environment variables alone when none exists (no crash on deploy).
_env = AutoConfig()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = _env('DJANGO_SECRET_KEY', default='django-insecure-dev-only-key')

DEBUG = _env('DJANGO_DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = _env(
    'DJANGO_ALLOWED_HOSTS',
    default='localhost,127.0.0.1,testserver',
    cast=lambda v: [h.strip() for h in v.split(',') if h.strip()],
)
# Dev and tunnel hosts stay available regardless of DJANGO_ALLOWED_HOSTS;
# .onrender.com covers the Render domain, and Render sets the exact public
# host in RENDER_EXTERNAL_HOSTNAME, which is appended when present.
for _host in ("localhost", "127.0.0.1", ".trycloudflare.com", ".onrender.com"):
    if _host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_host)
RENDER_EXTERNAL_HOSTNAME = _env('RENDER_EXTERNAL_HOSTNAME', default='')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = [
    "https://*.trycloudflare.com",
    "https://*.onrender.com",
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Project apps
    'accounts',
    'jobs',
    'candidates',
    'notifications',
    'pipeline',
    'feedback',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'altrium_tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'altrium_tracker.wsgi.application'


# Database
# Local development and production share the same PostgreSQL database,
# configured entirely through DATABASE_URL (Aiven in production).
# _env() reads real environment variables first, then the local .env file,
# so both Render and local development resolve the same Aiven connection.
DATABASES = {
    'default': dj_database_url.parse(
        _env('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Custom user model
AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'accounts:home'
LOGOUT_REDIRECT_URL = 'accounts:login'


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

# Media files (uploaded CVs)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Optional S3-compatible object storage (e.g. Cloudflare R2).
# Activates only when S3_ACCESS_KEY_ID and S3_BUCKET_NAME are set;
# otherwise media files use the local filesystem as before.
S3_ACCESS_KEY_ID = _env('S3_ACCESS_KEY_ID', default='')
S3_SECRET_ACCESS_KEY = _env('S3_SECRET_ACCESS_KEY', default='')
S3_BUCKET_NAME = _env('S3_BUCKET_NAME', default='')
S3_ENDPOINT = _env('S3_ENDPOINT', default='')
S3_PUBLIC_DOMAIN = _env('S3_PUBLIC_DOMAIN', default='')

if S3_ACCESS_KEY_ID and S3_BUCKET_NAME:
    _s3_custom_domain = None
    if S3_PUBLIC_DOMAIN:
        _s3_custom_domain = S3_PUBLIC_DOMAIN.split('://', 1)[-1]
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        'OPTIONS': {
            'access_key': S3_ACCESS_KEY_ID,
            'secret_key': S3_SECRET_ACCESS_KEY,
            'bucket_name': S3_BUCKET_NAME,
            'endpoint_url': S3_ENDPOINT or None,
            'region_name': 'auto',
            'default_acl': None,
            'querystring_auth': False,
            'custom_domain': _s3_custom_domain,
            'object_parameters': {'CacheControl': 'max-age=86400'},
        },
    }
    if S3_PUBLIC_DOMAIN:
        MEDIA_URL = f'{S3_PUBLIC_DOMAIN}/media/'


# Security settings - only enforced in production (DEBUG=False)
if not DEBUG:
    SECURE_SSL_REDIRECT = _env('DJANGO_SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = _env('DJANGO_SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'same-origin'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Groq AI
# Check environment variable first (Render dashboard), then fall back to .env file.
GROQ_API_KEY = _env('GROQ_API_KEY', default='')
GROQ_MODEL = _env('GROQ_MODEL', default='llama-3.3-70b-versatile')


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
