# Generated by Django 5.2.16 on 2026-08-02 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0003_alter_candidate_email'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text='Numeric score, e.g. 8/10.')),
                ('notes', models.TextField(help_text='Polished feedback (or original if not AI-assisted).')),
                ('raw_notes', models.TextField(blank=True, help_text='Original messy notes before AI polishing.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='candidates.jobapplication')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.interviewround')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_score', models.PositiveIntegerField()),
                ('old_notes', models.TextField()),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='feedback.interviewfeedback')),
            ],
            options={
                'verbose_name_plural': 'Feedback edit histories',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='interviewfeedback',
            constraint=models.UniqueConstraint(fields=('application', 'round', 'interviewer'), name='unique_feedback_per_round'),
        ),
    ]
