# Generated by Django 5.2.16 on 2026-09-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackedithistory',
            name='old_raw_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedbackedithistory',
            name='old_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
