# Generated by Django 5.2.16 on 2026-09-09 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackedithistory_old_raw_notes_and_more'),
        ('jobs', '0007_alter_job_auto_reject_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackedithistory',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edit_history', to='feedback.interviewfeedback'),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.interviewround'),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='score',
            field=models.PositiveIntegerField(help_text='Score from 0 to 100 (e.g. 75).'),
        ),
    ]
