# Generated by Django 5.2.16 on 2026-09-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remap_legacy_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='criteria_scores',
            field=models.JSONField(blank=True, default=list, help_text='Structured scorecard: list of {"criterion": <name>, "score": <0-100>}. Empty when the feedback used only the manual overall score.'),
        ),
    ]
