# Generated by Django 5.2.16 on 2026-09-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, default='', help_text='Functional area this interviewer covers (e.g. Engineering, Design, QA).', max_length=100),
        ),
    ]
