# Generated by Django 5.2.16 on 2026-09-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_intervieweravailability'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='intervieweravailability',
            constraint=models.UniqueConstraint(fields=('interviewer', 'weekday', 'start_time'), name='unique_availability_slot'),
        ),
    ]
