# Generated by Django 5.2.16 on 2026-09-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_intervieweravailability_unique_availability_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('infrastructure', 'Infrastructure'), ('quality_assurance', 'Quality Assurance'), ('design', 'Design'), ('product', 'Product'), ('data', 'Data'), ('other', 'Other')], default='', help_text='Structured domain, aligned with Job.Domain. Blank maps to blank (generalist).', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='seniority',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('lead', 'Lead')], default='', help_text='Interviewer seniority level. Must be at or above the job requirement to be assignable.', max_length=10),
        ),
    ]
