# Generated by Django 5.2.16 on 2026-09-22 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_force_password_change_user_photo_and_more'),
        ('candidates', '0014_jobapplication_general_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interview_buffer_minutes',
            field=models.PositiveSmallIntegerField(default=15, help_text="Minimum spacing (minutes) enforced between this interviewer's bookings, on top of the 60-minute slot window."),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone_char',
            field=models.CharField(blank=True, default='UTC', help_text="IANA timezone used to render this interviewer's own times. Storage stays UTC; only display is localized. Blank falls back to UTC.", max_length=64),
        ),
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_slot', models.DateTimeField()),
                ('proposed_slots', models.JSONField()),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='candidates.jobapplication')),
                ('requested_by', models.ForeignKey(limit_choices_to={'role': 'IV'}, on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_unavailable', models.BooleanField(default=True, help_text='True = blackout date (not available). False = extra hours (available beyond the weekly windows).')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interviewer', models.ForeignKey(limit_choices_to={'role': 'IV'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_unavailable', True), models.Q(('start_time__isnull', False), ('end_time__isnull', False), ('start_time__lt', models.F('end_time'))), _connector='OR'), name='exception_extra_hours_require_times'), models.UniqueConstraint(fields=('interviewer', 'date', 'start_time'), name='unique_availability_exception')],
            },
        ),
    ]
