# Generated by Django 5.2.16 on 2026-08-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='feedback_submitted',
            field=models.BooleanField(default=False, help_text='True once at least one feedback is submitted for the current round.'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_details',
            field=models.TextField(blank=True, help_text='Google Meet link and scheduling notes (visible to assigned interviewer).'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume_file',
            field=models.FileField(blank=True, upload_to='cvs/'),
        ),
    ]
