# Generated by Django 5.2.16 on 2026-08-03 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_jobapplication_feedback_submitted_and_more'),
        ('jobs', '0004_interviewround_ix_round_job_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['score'], name='ix_cand_score'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['-created_at'], name='ix_cand_created'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status'], name='ix_app_status'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['-updated_at'], name='ix_app_updated'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['current_round'], name='ix_app_round'),
        ),
    ]
