# Generated by Django 5.2.16 on 2026-08-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidate_ix_cand_score_candidate_ix_cand_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ai_fit_summary',
            field=models.TextField(blank=True, help_text='AI-generated candidate-vs-job fit assessment (Strengths / Gaps / Interview focus).'),
        ),
    ]
