# Generated by Django 5.2.16 on 2026-08-21 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_jobapplication_ai_fit_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='panel_interviewers',
            field=models.ManyToManyField(blank=True, help_text='Hiring panel interviewers assigned to evaluate this candidate.', related_name='panel_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
