# Generated by Django 5.2.16 on 2026-09-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_jobapplication_panel_interviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled interview start time for the assigned interviewer.', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='shortlist_score',
            field=models.IntegerField(blank=True, help_text='Score computed against this specific job (0-100), used for auto-reject.', null=True),
        ),
    ]
