# Generated by Django 5.2.16 on 2026-09-09 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_fix_interview_status'),
        ('jobs', '0007_alter_job_auto_reject_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['assigned_to'], name='ix_app_assigned_to'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['interview_at'], name='ix_app_interview_at'),
        ),
    ]
