# Generated by Django 5.2.16 on 2026-09-09 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_jobapplication_ix_app_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False, help_text='Set when the CV parse had low confidence and needs HR review.'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='needs_review_reasons',
            field=models.TextField(blank=True, default='', help_text='Comma-separated reasons for the review flag (e.g. no_email, low_text_volume).'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_candidates', to=settings.AUTH_USER_MODEL),
        ),
    ]
