# Generated by Django 5.2.16 on 2026-09-14 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_candidate_needs_review_and_more'),
        ('jobs', '0008_job_num_openings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='stage_entered_at',
            field=models.DateTimeField(blank=True, default=None, help_text='When the application last moved to its current round/status. Used for escalation timing and time-in-stage analytics; unlike updated_at, this only changes on a pipeline move.', null=True),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['stage_entered_at'], name='ix_app_stage_entered'),
        ),
    ]
