# Generated by Django 5.2.16 on 2026-09-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_backfill_stage_entered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='general_feedback',
            field=models.TextField(blank=True, help_text="AI-generated consolidated narrative across all of this application's round feedbacks (regenerated on each new feedback submission)."),
        ),
    ]
