/**
 * Playwright test-runner config for feature-transition regression tests.
 * Tests live in tests/feature-transitions/ and are organized around
 * feature-to-feature transitions, not pages.
 *
 * Usage:
 *   node node_modules/playwright/test.js test tests/feature-transitions
 *   (or: npx playwright test tests/feature-transitions)
 *
 * Auth: storage states are generated by qa/scripts/seed_auth_states.py and
 * stored under qa/storage-states/ (gitignored — never commit session state).
 */
// @ts-check
const path = require('node:path');
const { defineConfig, devices } = require('playwright/test');

const BASE_URL = process.env.QA_BASE_URL || 'http://127.0.0.1:8100';

module.exports = defineConfig({
  testDir: path.join(__dirname, '..', 'tests', 'feature-transitions'),
  timeout: 60_000,
  expect: { timeout: 8_000 },
  fullyParallel: false,      // shared Django dev DB; sequential keeps state predictable
  retries: process.env.CI ? 1 : 0,
  workers: 1,
  reporter: [
    ['list'],
    ['html', { outputFolder: 'tests/feature-transitions/artifacts/report', open: 'never' }],
  ],
  use: {
    baseURL: BASE_URL,
    trace: 'retain-on-failure',   // devtools evidence lands in artifacts/
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    actionTimeout: 10_000,
    navigationTimeout: 30_000,
    testIdAttribute: 'data-testid',
  },
  outputDir: 'tests/feature-transitions/artifacts',
  projects: [
    {
      name: 'chromium-desktop',
      use: { ...devices['Desktop Chrome'], viewport: { width: 1440, height: 900 } },
    },
    // Browser-matrix expansion point: add firefox / webkit projects here later.
    // The transition specs themselves must not hardcode chromium-only behavior.
  ],
});
